services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: habitask_db
      MYSQL_PASSWORD: sasa
    ports:
      - "3307:3307"
    volumes:
      - ./mysql:/var/lib/mysql

  user-authentication:
    build:
      context: ./  # Ruta base
      dockerfile: habit-ask-authentication/Dockerfile  # Dockerfile correcto
    ports:
      - "8080:8080"
    depends_on:
      - db

  user-tasks:
    build:
      context: ./  # Ruta base
      dockerfile: habit-ask-tasks/Dockerfile  # Dockerfile correcto
    ports:
      - "8081:8081"
    depends_on:
      - db

  user-notifications:
    build:
      context: ./  # Ruta base
      dockerfile: habit-ask-notifications/Dockerfile  # Dockerfile correcto
    ports:
      - "8082:8082"
    depends_on:
      - db